global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'hex_arch'

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['hex_arch_prometheus:9090']

  - job_name: 'mysqld_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['hex_arch_mysqld_exporter:9104']

  - job_name: 'api'
    scrape_interval: 5s
    static_configs:
      - targets: ['hex_arch_api:80']

#remote_write:
#  - url: http://cortex:9009/api/prom/push
#    queue_config:
#      capacity: 5000
#      max_shards: 20
#      min_shards: 5
#      max_samples_per_send: 1000